export const PolishPackages = [

    {
        id: 3,
        packageCat: 'Detailing Services',
        packageName: 'Paint Enhancement',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'One Step Polish remove swirls, scratches',
            'Clay Exterior Surfaces (Removes dirty & grime build up)',
            'Paint Decontamination (Iron Removal)',
            'Apply Wax/Sealant For Shine & Layer of Protection',
        ],
        // packagePriceTitle: 'Prices:',
        // packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/OneStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
    {
        id: 4,
        packageCat: 'Detailing Services',
        packageName: 'Paint correction',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'Polish paintwork 80%',
            'Finish off Paint work 20%',
            'Clay Exterior Surfaces for a smooth surface (Removes dirty & grime build up)',
            'Apply Wax/Sealant For Shine & Layer of Protection',
            'Final Wipe Down w/ Carnauba Wax',
        ],		
        // packagePriceTitle: 'Prices:',
        // packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/TwoStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
];