export const PolishPackages = [

    {
        id: 3,
        packageCat: 'Detailing Services',
        packageName: 'Paint Enhancement',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'One Step Polish remove swirls, scratches',
            'Clay Exterior Surfaces (Removes dirty & grime build up)',
            'Paint Decontamination (Iron Removal)',
            'Apply Wax/Sealant For Shine & Layer of Protection',
        ],
        // packagePriceTitle: 'Prices:',
        // packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/OneStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
    {
        id: 4,
        packageCat: 'Detailing Services',
        packageName: 'Paint Enhancement + 2yr Ceramic Coating',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'Clay Exterior Surfaces for a smooth surface (Removes dirty & grime build up)',
            'Paint Decontamination (Iron Removal)',
            'One Step Polish remove swirls, scratches.',
            'Apply Single Layer of Ceramic Coating For Ultimate Protection.',
            'Apply Wax/Sealant For Shine & Layer of Protection',
            'Final Wipe Down w/ Carnauba Wax',
        ],		
        // packagePriceTitle: 'Prices:',
        packagePriceArr: ['Prices vary on the condition of the vehicle. We also offer a 2For additional layers and services give us a call for a consultation today.'],
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/OneStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
    {
        id: 5,
        packageCat: 'Detailing Services',
        packageName: 'Paint correction',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'Clay Exterior Surfaces for a smooth surface (Removes dirty & grime build up)',
            'Polish paintwork 80%',
            'Finish off Paint work 20%',
            'Apply Wax/Sealant For Shine & Layer of Protection',
            'Apply Single Layer of Ceramic Coating For Ultimate Protection.',
            'Final Wipe Down w/ Carnauba Wax',
        ],		
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/TwoStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
    {
        id: 5,
        packageCat: 'Detailing Services',
        packageName: 'Paint correction + 2yr Ceramic Coating',
        packageDetailTitle: 'Package Includes:',
        packageDetailBullets: [
            'Express Detail package',
            'Clay Exterior Surfaces for a smooth surface (Removes dirty & grime build up)',
            'Polish paintwork 80%',
            'Finish off Paint work 20%',
            'Apply Wax/Sealant For Shine & Layer of Protection',
            'Final Wipe Down w/ Carnauba Wax',
        ],		
        packageEstimatedTimeTitle: 'Est. Time:',
        packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
        tNailSRC: '/Assets/Images/TwoStepPolish.jpg',
        PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
    },
    {
    id: 6,
    packageCat: 'Cleaning Services',
    packageName: 'Deep Interior Cleaning with Express Detail',
    packageDetailTitle: 'Package Includes:',
    packageDetailBullets: [
        'Express Detail package', 
        'Deep Clean Wheels, Tires, Fenders, Gas Cap',  
        'Cleaning Interior Glass & Windows', 
        'Wiping Down Dust Of All Surfaces', 
        'Steam Cleaning & Shampoo carpert extraction', 
        'Cleaning & Conditioning Leather & Trim', 
    ],
    // packagePriceTitle: 'Prices:',
    // packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
    packageEstimatedTimeTitle: 'Est. Time:',
    packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
    tNailSRC: '/Assets/Images/PricingTnails/DeepInteriorCleaning.jpg',
    PackageDetailParagraph: 'Through interior cleaning and shampooing package.',
},
{
    id: 7,
    packageCat: 'Cleaning Services',
    packageName: 'Engine Cleaning',
    packageDetailTitle: 'Package Includes:',
    packageDetailBullets: [
        'Cover Sensitive Areas', 
        'Softly Rinse Engine Bay', 
        'Clean & Degrease All Surfaces', 
        'Dressing All Plastic & Vinyl'
    ],
    packagePriceTitle: 'Prices:',
    packagePriceArr: [ 'Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
    packageEstimatedTimeTitle: 'Est. Time:',
    packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
    tNailSRC: '/Assets/Images/PricingTnails/EngineCleaning.jpg',
    PackageDetailParagraph: 'Complete engine and engine bay cleaning package.',
},
];