export const WashPackages = [
	{
		id: 0,
		packageCat: 'Detailing Services',
		packageName: 'Express Detail',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: ['Hand Wash w/ new microfiber towel', 'Deep clean Wheels, Tires, Fenders, Gas Cap', 'Air dry with filtered air ', 'Wipe Down Door Jambs, Cup Holders, and Center Console ', 'Thorough Vacuum ', 'Clean Exterior Glass & Windows', 'Dress Tires', 'Final Wipe Down w/ Carnauba Wax ', '(All chemicals used are of high quality & are water based to avoid any damage to vehicle)'],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/ExpressDetail.jpg',
		PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
	},
	{
		id: 1,
		packageCat: 'Detailing Services',
		packageName: 'Detail Wash & Wax',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [ 
			'Hand Wash w/ new microfiber towel', 
			'Deep clean Wheels, Tires, Fenders, Gas Cap', 
			'Clay exterior surfaces (Removes dirty & grime build up)', 
			'Paint Decontamination (Iron Removal)', 
			'Air dry with filtered air ', 
			'Apply Wax/Sealant For Shine & Layer of Protection', 
			'Wipe Down Door Jambs, Cup Holders, and Center Console ',
			'Thorough Vacuum ',
			'Clean Exterior Glass & Windows' ,
			'Dress Tires & fenders', 
			'Dress Exterior Trims', 
			'Final Wipe Down w/ Carnauba Wax ',
			'(All chemicals used are of high quality & are water based to avoid any damage to vehicle)' 
			],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],

		tNailSRC: '/Assets/Images/PricingTnails/DetailWashNWax.jpg',
		PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
	},
	{
		id: 2,
		packageCat: 'Complete Package',
		packageName: 'All in One Service & Light Polish',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [
			'Hand Wash w/ new microfiber towel',
			'Deep clean Wheels, Tires, Fenders, Gas Cap',
			'Clay exterior surfaces (Removes dirty & grime build up)', 
			'Light Polish with All in One compound',
			'Paint Decontamination (Iron Removal)', 
			'Air dry with filtered air ', 
			'Apply Wax/Sealant For Shine & Layer of Protection', 
			'Wipe Down Door Jambs, Cup Holders, and Center Console ',
			'Clay exterior surfaces',
			'Apply Wax/Sealant For Shine & Layer of Protection',
			'Clean exterior glass and windows',
			'Dress tires and fenders',
			'Dress exterior trim',
			'Clean and polish emblems',
			'Polish wheels',
			'Final Wipe Down w/ Carnauba Wax',
		],
		packagePriceTitle: 'Prices:',
		packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/AllInOneCleaning.jpg',
		PackageDetailParagraph: 'All encompassing vehicle detailing package.',
	},
];
