export const WashPackages = [
	{
		id: 0,
		packageCat: 'Detailing Services',
		packageName: 'Express Detail',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [
			'100 % Hand Wash w/ Brand New Microfiber Towel', 
			'Deep clean Wheels, Tires, Fenders, Gas Cap', 
			'Air Dry w/ Filter Air (Prevents Micro-scratching) ', 
			'Wipe Down Door Jambs, Cup Holders, and Center Console ', 
			'Thorough Vacuum ', 
			'Clean Exterior Glass & Windows', 
			'Dress Tires & Fenders', 
			'Final Wipe Down w/ Detail Spray ',
			'(All chemicals used are of high quality & are water based to avoid any damage to vehicle) '
		],
		// packagePriceTitle: 'Prices:',
		// packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/ExpressDetail.jpg',
		PackageDetailParagraph: 'Quick and affordable exterior detailing package.',
		packageDepositTitle: 'Deposits: ',
		packageDeposit: ['There is a $20 dollar deposit that is due when appointment is confirmed. This will be added to the total after service is complete. CANCELLATIONS: If cancelled within 24 hours of the appointment scheduled time $20 deposit is non-refundable. ']	},
	{
		id: 1,
		packageCat: 'Detailing Services',
		packageName: 'Detail Wash & Wax',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [ 
			'Express Detail package',
			'Clay exterior surfaces (Removes dirty & grime build up) *', 
			'Paint Decontamination (Removes Iron Contamination from Paint) *', 
			'Apply Wax/Sealant For Shine & Layer of Protection *',
			'Final Wipe Down w/ Carnauba Wax Spray',
			'(All chemicals used are of high quality & are water based to avoid any damage to vehicle) '
			],
		// packagePriceTitle: 'Prices:',
		// packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],

		tNailSRC: '/Assets/Images/PricingTnails/DetailWashNWax.jpg',
		PackageDetailParagraph: 'Specialized vehicle exterior detailing package.',
		packageDepositTitle: 'Deposits: ',
		packageDeposit: ['There is a $20 dollar deposit that is due when appointment is confirmed. This will be added to the total after service is complete. CANCELLATIONS: If cancelled within 24 hours of the appointment scheduled time $20 deposit is non-refundable. ']
	},
	{
		id: 2,
		packageCat: 'Complete Package',
		packageName: 'All in One Service & Light Polish',
		packageDetailTitle: 'Package Includes:',
		packageDetailBullets: [
			'Express Detail package',
			' Deep Clean Wheels, Tires, Fenders, Gas Cap *',
			'Paint Decontamination (Removes Iron Contamination from Paint) *', 
			'Clay exterior surfaces (Removes dirty & grime build up) *', 
			'Light Polish with All in One compound. (Removes Micro-Scratches, Light Oxidation, Adds Protection ) *',
			'Apply Wax/Sealant For Shine & Layer of Protection', 
			'Clean and polish emblems',
			'Final Wipe Down w/ Carnauba Wax Spray',
			'(All chemicals used are of high quality & are water based to avoid any damage to vehicle) '

		],
		packageBonusTitle: 'Bonus',
		packageBonusArr: ['Interior Leather/Plastic Parts Reconditioning', 'Dress Exterior Trims (Recondition of Black Trims)'],
		// packagePriceTitle: 'Prices:',
		// packagePriceArr: ['Additional Fees will be applied for Pet Hair, Extra Dirty Vehicles, Mud & heavily soiled interiors. For an accurate quote please contact me via phone at (818)915-1828. There is a $20 dollar cancellation fee if cancelled within 12 hours of appointment.'],
		packageEstimatedTimeTitle: 'Est. Time:',
		packageEstimatedTimeArr: ['The time for this service will depend on the current condition of the vehicle. Please call or send an email to request a quote'],
		tNailSRC: '/Assets/Images/PricingTnails/AllInOneCleaning.jpg',
		PackageDetailParagraph: 'All encompassing vehicle detailing package.',
		packageDepositTitle: 'Deposits: ',
		packageDeposit: ['There is a $20 dollar deposit that is due when appointment is confirmed. This will be added to the total after service is complete. CANCELLATIONS: If cancelled within 24 hours of the appointment scheduled time $20 deposit is non-refundable. ']	},
];
